apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: myweb-demo
  namespace: default
spec:
  selector:
    matchLabels:
    app: myweb
    release: demo
  fileGroups:
  - path: /source/data
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: myweb-demo
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true

